Start adding Android cross-compilation support.

diff --git a/build/bashrc b/build/bashrc
--- a/build/bashrc
+++ b/build/bashrc
@@ -3,6 +3,12 @@
 case $FRIDA_TARGET in
   linux)
     ;;
+  android)
+    if [ -z "$ANDROID_NDK_ROOT" ]; then
+      echo "ERROR: ANDROID_NDK_ROOT must be set"
+      exit 1
+    fi
+    ;;
   osx)
     ;;
   ios)
@@ -23,64 +29,113 @@ export FRIDA_PREFIX_LIB="${FRIDA_PREFIX}/lib"
 export FRIDA_TOOLROOT="${FRIDA_BUILD}/toolchain"
 export FRIDA_SDKROOT="${FRIDA_BUILD}/sdk-${FRIDA_TARGET}"
 
-if [ "$FRIDA_TARGET" = "linux" ]; then
-  export PATH="${FRIDA_PREFIX}/bin:${PATH}"
-else
-  export PATH="${FRIDA_TOOLROOT}/bin:${IOS_DEVROOT}/usr/bin:/opt/local/bin:${PATH}"
+case $FRIDA_TARGET in
+  linux)
+    export PATH="${FRIDA_PREFIX}/bin:${PATH}"
+    ;;
+  android)
+    ndk_target_platfom="platform-8"
+    ndk_tools_root="${ANDROID_NDK_ROOT}/build/prebuilt/darwin-x86/arm-eabi-4.4.0"
+    ndk_platform_root="${ANDROID_NDK_ROOT}/build/platforms/${ndk_target_platfom}/arch-arm"
 
-  export MACOSX_DEPLOYMENT_TARGET=10.6
-  export CLICOLOR=1
-fi
+    export PATH="${FRIDA_TOOLROOT}/bin:${ndk_tools_root}/bin:${PATH}"
+    export CLICOLOR=1
+    ;;
+  *)
+    export PATH="${FRIDA_TOOLROOT}/bin:${IOS_DEVROOT}/usr/bin:/opt/local/bin:${PATH}"
+
+    export MACOSX_DEPLOYMENT_TARGET=10.6
+    export CLICOLOR=1
+    ;;
+esac
 
 export PS1="\e[0;33m[\u@\h \w \e[m\e[1;33mfrida-${FRIDA_TARGET}\e[m\e[0;33m]\e[m\n\$ "
 
-if [ "$FRIDA_TARGET" = "osx" ]; then
-  export CC="/usr/bin/gcc-4.2"
-  export CXX="/usr/bin/g++-4.2"
-  export OBJC="/usr/bin/gcc-4.2"
+case $FRIDA_TARGET in
+  linux)
+    export CC="gcc"
+    export CXX="g++"
 
-  export CFLAGS=""
-  export LDFLAGS=""
-elif [ "$FRIDA_TARGET" = "ios" ]; then
-  export IOS_SDKVER="4.2"
-  export IOS_MINVER="4.0"
-  export IOS_DEVROOT="/Developer/Platforms/iPhoneOS.platform/Developer"
-  export IOS_SDKROOT="${IOS_DEVROOT}/SDKs/iPhoneOS${IOS_SDKVER}.sdk"
+    export CFLAGS="-ffunction-sections -fdata-sections"
+    export LDFLAGS="-Wl,--gc-sections"
+    ;;
+  android)
+    export CC=""
+    export CXX=""
 
-  export CC="${IOS_DEVROOT}/usr/bin/gcc-4.2"
-  export CXX="${IOS_DEVROOT}/usr/bin/g++-4.2"
-  export OBJC="${IOS_DEVROOT}/usr/bin/gcc-4.2"
+    export CFLAGS="\
+--sysroot=${ndk_platform_root} \
+-fpic \
+-mthumb-interwork \
+-ffunction-sections \
+-funwind-tables \
+-fstack-protector \
+-fno-short-enums \
+-D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ \
+-D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ \
+-Wno-psabi \
+-march=armv7-a \
+-mfloat-abi=softfp \
+-mfpu=vfp \
+-Wa,--noexecstack"
+    export LDFLAGS="\
+-Wl,--sysroot=${ndk_platform_root} \
+-Wl,--fix-cortex-a8 \
+-Wl,--no-undefined \
+-Wl,-z,noexecstack"
+    ;;
+  osx)
+    export CC="/usr/bin/gcc-4.2"
+    export CXX="/usr/bin/g++-4.2"
+    export OBJC="/usr/bin/gcc-4.2"
 
-  export CFLAGS="-isysroot ${IOS_SDKROOT} -miphoneos-version-min=${IOS_MINVER} -arch armv7"
-  export LDFLAGS="-isysroot ${IOS_SDKROOT} -Wl,-iphoneos_version_min,${IOS_MINVER} -arch armv7"
-else
-  export CC="gcc"
-  export CXX="g++"
+    export CFLAGS=""
+    export LDFLAGS=""
+    ;;
+  ios)
+    export IOS_SDKVER="4.2"
+    export IOS_MINVER="4.0"
+    export IOS_DEVROOT="/Developer/Platforms/iPhoneOS.platform/Developer"
+    export IOS_SDKROOT="${IOS_DEVROOT}/SDKs/iPhoneOS${IOS_SDKVER}.sdk"
 
-  export CFLAGS="-ffunction-sections -fdata-sections"
-  export LDFLAGS="-Wl,--gc-sections"
-fi
+    export CC="${IOS_DEVROOT}/usr/bin/gcc-4.2"
+    export CXX="${IOS_DEVROOT}/usr/bin/g++-4.2"
+    export OBJC="${IOS_DEVROOT}/usr/bin/gcc-4.2"
+
+    export CFLAGS="-isysroot ${IOS_SDKROOT} -miphoneos-version-min=${IOS_MINVER} -arch armv7"
+    export LDFLAGS="-isysroot ${IOS_SDKROOT} -Wl,-iphoneos_version_min,${IOS_MINVER} -arch armv7"
+    ;;
+esac
 
 export LD="${CC}"
-export LDFLAGS="$LDFLAGS -no-undefined"
+if [ ! $FRIDA_TARGET = android ]; then
+  export LDFLAGS="$LDFLAGS -no-undefined"
+fi
 
 export CXXFLAGS="$CFLAGS"
 export OBJCFLAGS="$CFLAGS"
 export CPPFLAGS="$CFLAGS"
 
-if [ "$FRIDA_TARGET" = "linux" ]; then
-  export ACLOCAL_FLAGS="-I ${FRIDA_PREFIX}/share/aclocal"
+case $FRIDA_TARGET in
+  linux)
+    export ACLOCAL_FLAGS="-I ${FRIDA_PREFIX}/share/aclocal"
 
-  export PKG_CONFIG_PATH="${FRIDA_PREFIX_LIB}/pkgconfig"
-  export VALAC="${FRIDA_PREFIX}/bin/valac-0.10 --vapidir=\"${FRIDA_PREFIX}/share/vala/vapi\""
-else
-  export ACLOCAL_FLAGS="-I ${FRIDA_PREFIX}/share/aclocal -I ${FRIDA_SDKROOT}/share/aclocal -I ${FRIDA_TOOLROOT}/share/aclocal"
-  export LDFLAGS="$LDFLAGS -Wl,-dead_strip -Wl,-headerpad_max_install_names"
+    export PKG_CONFIG_PATH="${FRIDA_PREFIX_LIB}/pkgconfig"
+    export VALAC="${FRIDA_PREFIX}/bin/valac-0.10 --vapidir=\"${FRIDA_PREFIX}/share/vala/vapi\""
+    ;;
+  android)
+    export FRIDA_SDKROOT=""
+    ;;
+  osx|ios)
+    export ACLOCAL_FLAGS="-I ${FRIDA_PREFIX}/share/aclocal -I ${FRIDA_SDKROOT}/share/aclocal -I ${FRIDA_TOOLROOT}/share/aclocal"
+    export LDFLAGS="$LDFLAGS -Wl,-dead_strip -Wl,-headerpad_max_install_names"
 
-  export PKG_CONFIG="${FRIDA_TOOLROOT}/bin/pkg-config --define-variable=frida_sdk_prefix=${FRIDA_SDKROOT} --static"
-  export PKG_CONFIG_PATH="${FRIDA_PREFIX_LIB}/pkgconfig:${FRIDA_SDKROOT}/lib/pkgconfig:${IOS_SDKROOT}/usr/lib/pkgconfig"
-  export VALAC="${FRIDA_TOOLROOT}/bin/valac-0.10 --vapidir=\"${FRIDA_TOOLROOT}/share/vala-0.10/vapi\" --vapidir=\"${FRIDA_SDKROOT}/share/vala/vapi\" --vapidir=\"${FRIDA_PREFIX}/share/vala/vapi\""
-fi
+    export PKG_CONFIG="${FRIDA_TOOLROOT}/bin/pkg-config --define-variable=frida_sdk_prefix=${FRIDA_SDKROOT} --static"
+    export PKG_CONFIG_PATH="${FRIDA_PREFIX_LIB}/pkgconfig:${FRIDA_SDKROOT}/lib/pkgconfig:${IOS_SDKROOT}/usr/lib/pkgconfig"
+    export VALAC="${FRIDA_TOOLROOT}/bin/valac-0.10 --vapidir=\"${FRIDA_TOOLROOT}/share/vala-0.10/vapi\" --vapidir=\"${FRIDA_SDKROOT}/share/vala/vapi\" --vapidir=\"${FRIDA_PREFIX}/share/vala/vapi\""
+    ;;
+esac
+
 export ACLOCAL="aclocal ${ACLOCAL_FLAGS}"
 export CONFIG_SITE="${FRIDA_BUILD}/config.site"
 
@@ -93,9 +148,11 @@ if [ ! "$FRIDA_TARGET" = "linux" ]; then
     curl -sS "http://frida-ire.googlecode.com/files/toolchain-osx-20101220.tar.bz2" | tar -C "${FRIDA_BUILD}" -xj - || exit 1
   fi
 
-  if [ ! -d "${FRIDA_BUILD}/sdk-${FRIDA_TARGET}" ]; then
-    echo "Downloading and deploying SDK for ${FRIDA_TARGET}..."
-    curl -sS "http://frida-ire.googlecode.com/files/sdk-${FRIDA_TARGET}-20101003.tar.bz2" | tar -C "${FRIDA_BUILD}" -xj - || exit 1
+  if [ ! "$FRIDA_TARGET" = "android" ]; then
+    if [ ! -d "${FRIDA_BUILD}/sdk-${FRIDA_TARGET}" ]; then
+      echo "Downloading and deploying SDK for ${FRIDA_TARGET}..."
+      curl -sS "http://frida-ire.googlecode.com/files/sdk-${FRIDA_TARGET}-20101003.tar.bz2" | tar -C "${FRIDA_BUILD}" -xj - || exit 1
+    fi
   fi
 
   for template in $(find ${FRIDA_TOOLROOT} ${FRIDA_SDKROOT} -name "*.frida.in"); do
