Start moving towards generic build infrastructure on UNIX.

diff --git a/build/bashrc b/build/bashrc
--- a/build/bashrc
+++ b/build/bashrc
@@ -1,32 +1,54 @@
 [ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"
 
+case $FRIDA_TARGET in
+  osx|ios)
+    ;;
+  *)
+    echo "Invalid FRIDA_TARGET, must be either osx or ios"
+    exit 1
+    ;;
+esac
+
 export FRIDA_ROOT="$(pwd)"
 export FRIDA_BUILD="${FRIDA_ROOT}/build"
-export FRIDA_PREFIX="${FRIDA_BUILD}/armv7"
+export FRIDA_PREFIX="${FRIDA_BUILD}/frida-${FRIDA_TARGET}"
 export FRIDA_PREFIX_LIB="${FRIDA_PREFIX}/lib"
 export FRIDA_TOOLROOT="${FRIDA_BUILD}/toolchain"
-export FRIDA_SDKROOT="${FRIDA_BUILD}/sdk"
+export FRIDA_SDKROOT="${FRIDA_BUILD}/sdk-${FRIDA_TARGET}"
 
-export IPHONE_SDKVER="4.0"
-export IPHONE_DEVROOT="/Developer/Platforms/iPhoneOS.platform/Developer"
-export IPHONE_SDKROOT="${IPHONE_DEVROOT}/SDKs/iPhoneOS${IPHONE_SDKVER}.sdk"
 export MACOSX_DEPLOYMENT_TARGET=10.6
 
 export PATH="${FRIDA_TOOLROOT}/bin:${IPHONE_DEVROOT}/usr/bin:/opt/local/bin:${PATH}"
-export PS1="\e[0;33m[\u@\h \w \e[m\e[1;33mfrida-iphone\e[m\e[0;33m]\e[m\n\$ "
+export PS1="\e[0;33m[\u@\h \w \e[m\e[1;33mfrida-${FRIDA_TARGET}\e[m\e[0;33m]\e[m\n\$ "
 export CLICOLOR=1
 
-export CC="${IPHONE_DEVROOT}/usr/bin/gcc-4.2"
-export CXX="${IPHONE_DEVROOT}/usr/bin/g++-4.2"
-export OBJC="${IPHONE_DEVROOT}/usr/bin/gcc-4.2"
+if [ "$FRIDA_TARGET" = "osx" ]; then
+  export CC="/usr/bin/gcc-4.2"
+  export CXX="/usr/bin/g++-4.2"
+  export OBJC="/usr/bin/gcc-4.2"
+
+  export CFLAGS=""
+  export LDFLAGS=""
+else
+  export IPHONE_SDKVER="4.0"
+  export IPHONE_DEVROOT="/Developer/Platforms/iPhoneOS.platform/Developer"
+  export IPHONE_SDKROOT="${IPHONE_DEVROOT}/SDKs/iPhoneOS${IPHONE_SDKVER}.sdk"
+
+  export CC="${IPHONE_DEVROOT}/usr/bin/gcc-4.2"
+  export CXX="${IPHONE_DEVROOT}/usr/bin/g++-4.2"
+  export OBJC="${IPHONE_DEVROOT}/usr/bin/gcc-4.2"
+
+  export CFLAGS="-isysroot ${IPHONE_SDKROOT} -miphoneos-version-min=${IPHONE_SDKVER} -arch armv7"
+  export LDFLAGS="-isysroot ${IPHONE_SDKROOT} -Wl,-iphoneos_version_min,${IPHONE_SDKVER} -arch armv7"
+fi
+
 export LD="${CC}"
 export VALAC="${FRIDA_TOOLROOT}/bin/valac --vapidir=\"${FRIDA_SDKROOT}/share/vala/vapi\""
 
-export CFLAGS="$CFLAGS -isysroot ${IPHONE_SDKROOT} -miphoneos-version-min=${IPHONE_SDKVER} -arch armv7"
 export CXXFLAGS="$CFLAGS"
 export OBJCFLAGS="$CFLAGS"
 export CPPFLAGS="$CFLAGS"
-export LDFLAGS="-isysroot ${IPHONE_SDKROOT} -Wl,-iphoneos_version_min,${IPHONE_SDKVER} -arch armv7 -Wl,-dead_strip -Wl,-headerpad_max_install_names"
+export LDFLAGS="$LDFLAGS -Wl,-dead_strip -Wl,-headerpad_max_install_names"
 
 export ACLOCAL_FLAGS="-I ${FRIDA_PREFIX}/share/aclocal -I ${FRIDA_SDKROOT}/share/aclocal -I ${FRIDA_TOOLROOT}/share/aclocal"
 export ACLOCAL="aclocal ${ACLOCAL_FLAGS}"
